[[mgr.prepend_keymap]]
on = "o"
run = "open --interactive"
desc = "Open with picker"



[[mgr.prepend_keymap]]
on   = [ "g", "b" ]
run  = 'shell -- awww img %h && wal -i %h --contrast 1'
desc = "Set wall + pywal"


[[mgr.prepend_keymap]]
on   = [ "c", "l" ]
run = '''
    shell 'for f in $YAZI_SELECTED; do echo "$f"; done | wl-copy' --confirm
'''
desc = "Copy actual file to clipboard"

[[mgr.prepend_keymap]]
on   = [ "g", "w" ]
run  = 'cd ~/WALLPAPERS'
desc = "Go ~/WALLPAPERS"
