# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf

$font = JetBrainsMono Nerd Font Propo
source= mocha.conf

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor = 
    path = ~/WALLPAPERS/retro-room.png
    blur_passes = 1
    blur_size = 3
}
# Profile Picture
image {
    monitor =
    path = ~/WALLPAPERS/6309855404132865056.jpg
    size = 100
    border_size = 10
    border_color = rgba($textAlpha33)
    position = 0, 250
    halign = center
    valign = bottom
}


#user
label {
    monitor =
    # text = cmd[update:1000] whoami
    text =$USER
    font_family = $font
    color = $light1
    position = 0, 220
    halign = center
    valign = bottom
}

input-field {
    monitor =
    size = 200, 30
    outline_thickness = 3
    inner_color = rgba($textAlpha33)

    # outer_color = $green $sapphire 30deg
    # check_color = $red $peach 120deg
    # fail_color = $red $peach 30deg

    outer_color = rgba($textAlpha33)
    check_color = $red
    fail_color = $red

    font_color = rgba($textAlpha99)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = 
    fail_text = 

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, 180
    halign = center
    valign = bottom
}



# TIME
label {
    monitor =
    text = cmd[update:1]  date +"%l:%M"
    font_size = 120
    font_family = $font black
    position = 0, -200
    halign = center
    valign = top
    color = rgba($textAlpha55)
}

# day
label {
    monitor =
    text = cmd[update:1] date +"%a"
    font_size = 16
    font_family = $font
    position = -150, -380
    halign = center
    valign = top
    color = $text
}

#separator
label {
    monitor =
    text = 
    font_size = 14
    font_family = $font
    position = -100, -382
    halign = center
    valign = top
    color=$red
}

# date
label {
    monitor =
    text = cmd[update:1] date +"%e"
    font_size = 16
    font_family = $font
    position = -50, -380
    halign = center
    valign = top
    color = $text
}
#separator
label {
    monitor =
    text = 
    font_size = 14
    font_family = $font
    position = 0, -382
    halign = center
    valign = top
    color=$green
}

# month
label {
    monitor =
    text = cmd[update:1] date +"%b"
    font_size = 16
    font_family = $font
    position = 50, -380
    halign = center
    valign = top
    color = $text
}
#separator
label {
    monitor =
    text = 
    font_size = 14
    font_family = $font
    position = 100, -382
    halign = center
    valign = top
    color=$blue
}
# Year
label {
    monitor =
    text = cmd[update:1] date +"%Y"
    font_size = 16
    font_family = $font
    position = 150, -380
    halign = center
    valign = top
    color = $text
}
